services:
  vm1:
    build: .
    ports:
      - "2022:22"
      - "8080:80"
      - "8443:443"
  vm2:
    build: .
    ports:
      - "2023:22"
      - "8081:80"
      - "8444:443"
  vm3:
    build: .
    ports:
      - "2024:22"
      - "8082:80"
      - "8445:443"
  vm4:
    build: .
    ports:
      - "2025:22"
      - "8083:80"
      - "8446:443"